"""
Phase 4 M2: Post-transplant outcomes service.

Provides center-level graft and patient survival data from SRTR PSR Tables C5-C12
and C11-C20. Computes the compound success metric:
    P(transplant within 24mo) x P(1yr graft survival)

Data source: data/post-transplant-outcomes.json (generated by parse-srtr-reports.py).
"""
import logging

from services.data_loader import get_data

logger = logging.getLogger(__name__)

# Valid organs for outcomes lookup
VALID_ORGANS = {"kidney", "liver", "heart", "lung", "pancreas", "intestine"}

# Minimum graft survival for compound metric (below this, data is suspect)
MIN_SURVIVAL_PCT = 50.0


def _get_outcomes_data() -> dict:
    """Get the post-transplant outcomes dict from loaded data."""
    return get_data().post_transplant_outcomes


def get_city_outcomes(organ: str, city: str = "", center_code: str = "") -> dict | None:
    """
    Get post-transplant outcomes for a specific center/city and organ.
    Prefers center-code lookup; falls back to city-level data.
    Returns None if data is unavailable.
    """
    if organ not in VALID_ORGANS:
        return None
    data = get_data()
    # Prefer center-code lookup from center-level outcomes
    if center_code:
        center_outcomes = data.center_outcomes.get("center_outcomes", {})
        center_data = center_outcomes.get(center_code, {})
        result = center_data.get(organ)
        if result:
            return result
    # Fall back to city-level outcomes
    city_outcomes = _get_outcomes_data().get("city_outcomes", {})
    city_data = city_outcomes.get(city, {})
    return city_data.get(organ) or None


def get_national_baselines(organ: str) -> dict | None:
    """
    Get national baseline survival rates for an organ.
    Returns dict with national_graft_survival_1yr, national_patient_survival_1yr, etc.
    """
    if organ not in VALID_ORGANS:
        return None
    data = _get_outcomes_data()
    return data.get(organ) or None


def get_graft_survival_1yr(organ: str, city: str = "", center_code: str = "") -> float | None:
    """
    Get 1-year graft survival rate for a center (as a percentage, e.g. 95.0).
    Falls back to national average if center data unavailable.
    """
    outcomes = get_city_outcomes(organ, city, center_code=center_code)
    if outcomes and outcomes.get("graft_survival_1yr") is not None:
        return outcomes["graft_survival_1yr"]
    # Fall back to national
    baselines = get_national_baselines(organ)
    if baselines:
        return baselines.get("national_graft_survival_1yr")
    return None


def get_patient_survival_1yr(organ: str, city: str = "", center_code: str = "") -> float | None:
    """
    Get 1-year patient survival rate for a center (as a percentage).
    Falls back to national average if center data unavailable.
    """
    outcomes = get_city_outcomes(organ, city, center_code=center_code)
    if outcomes and outcomes.get("patient_survival_1yr") is not None:
        return outcomes["patient_survival_1yr"]
    baselines = get_national_baselines(organ)
    if baselines:
        return baselines.get("national_patient_survival_1yr")
    return None


def compute_compound_success(p_transplant_24mo: float, graft_survival_1yr_pct: float | None) -> float | None:
    """
    Compute compound success metric: P(transplant within 24mo) x P(1yr graft survival).

    Args:
        p_transplant_24mo: Probability of transplant within 24 months (0-1).
        graft_survival_1yr_pct: 1-year graft survival rate as percentage (0-100).

    Returns:
        Compound success probability (0-1), or None if graft survival unavailable.
    """
    if graft_survival_1yr_pct is None or graft_survival_1yr_pct < MIN_SURVIVAL_PCT:
        return None
    return p_transplant_24mo * (graft_survival_1yr_pct / 100.0)


def build_outcomes_dict(organ: str, city: str = "", p_transplant_24mo: float = 0.0, center_code: str = "") -> dict | None:
    """
    Build the complete outcomes dict for a center/city, ready to attach to CityProbability.
    Returns None if no outcomes data available for this organ/center.
    """
    outcomes = get_city_outcomes(organ, city, center_code=center_code)
    baselines = get_national_baselines(organ)

    # Need at least baselines to be useful
    if not baselines and not outcomes:
        return None

    result = {}

    # Graft survival
    gs_1yr = get_graft_survival_1yr(organ, city, center_code=center_code)
    if gs_1yr is not None:
        result["graft_survival_1yr"] = round(gs_1yr / 100.0, 4)

    # Patient survival
    ps_1yr = get_patient_survival_1yr(organ, city, center_code=center_code)
    if ps_1yr is not None:
        result["patient_survival_1yr"] = round(ps_1yr / 100.0, 4)

    # National baselines (as decimals)
    if baselines:
        nat_gs = baselines.get("national_graft_survival_1yr")
        nat_ps = baselines.get("national_patient_survival_1yr")
        if nat_gs is not None:
            result["national_graft_survival_1yr"] = round(nat_gs / 100.0, 4)
        if nat_ps is not None:
            result["national_patient_survival_1yr"] = round(nat_ps / 100.0, 4)

    # Hazard ratio and CI (from center-specific data only)
    if outcomes:
        if outcomes.get("graft_hr_1yr") is not None:
            result["graft_hr_1yr"] = outcomes["graft_hr_1yr"]
        if outcomes.get("graft_hr_1yr_ci"):
            result["graft_hr_1yr_ci"] = outcomes["graft_hr_1yr_ci"]
        if outcomes.get("performance_rating"):
            result["performance_rating"] = outcomes["performance_rating"]
        if outcomes.get("n_1yr") is not None:
            result["n_1yr"] = outcomes["n_1yr"]

    # Compound success metric — prefer graft survival, fall back to patient survival
    # (pancreas lacks adult graft survival data; patient survival is a valid proxy)
    survival_for_compound = gs_1yr if gs_1yr is not None else ps_1yr
    compound = compute_compound_success(p_transplant_24mo, survival_for_compound)
    if compound is not None:
        result["compound_success"] = round(compound, 4)
        if gs_1yr is None and ps_1yr is not None:
            result["compound_success_note"] = "Uses patient survival (graft survival unavailable for this organ)"

    # Only return if we have meaningful data
    if "graft_survival_1yr" in result or "patient_survival_1yr" in result:
        return result
    return None
