"""
Phase 4 M3: Historical trends & center trajectory analysis.

Uses multi-year SRTR data to compute trend direction and significance for
each city's transplant metrics: wait times, volumes, and graft survival.

Data source: data/srtr-historical.json (generated by parse-srtr-reports.py).
"""
import logging
from typing import Optional

import numpy as np
from scipy import stats

from services.data_loader import get_data

logger = logging.getLogger(__name__)

# Valid organs
VALID_ORGANS = {"kidney", "liver", "heart", "lung", "pancreas", "intestine"}

# Minimum data points for a meaningful regression (issue #58: raised from 3)
MIN_POINTS = 5

# p-value threshold for declaring a trend statistically significant
# (issue #58: tightened from 0.10 to standard 0.05)
P_VALUE_THRESHOLD = 0.05

# Minimum R² for practical significance — even a statistically significant
# trend is labeled "stable" if R² is below this (issue #58)
MIN_R_SQUARED = 0.3

# Minimum annual change thresholds (to avoid declaring noise as a trend)
# These are absolute values per year — the metric must be changing at least
# this fast to be classified as improving/declining
MIN_ANNUAL_CHANGE = {
    "median_wait_months": 0.5,    # 0.5 months/year
    "volume": 3.0,                # 3 transplants/year
    "graft_survival_1yr": 0.2,    # 0.2 percentage points/year
    "patient_survival_1yr": 0.2,
    "mortality_rate": 0.001,      # 0.1 ppt/year
    "delisting_rate": 0.002,
}


def _get_historical_data() -> dict:
    """Get the historical trends dict from loaded data."""
    return get_data().historical_trends


def _compute_metric_trend(
    years: list[int],
    values: list[float | None],
    metric_name: str,
) -> dict:
    """
    Compute trend for a single metric time series.

    Returns dict with: years, values, slope, p_value, direction, change_per_year.
    """
    # Filter out None values
    valid_pairs = [(y, v) for y, v in zip(years, values) if v is not None]

    if len(valid_pairs) < MIN_POINTS:
        return {
            "years": years,
            "values": values,
            "slope": None,
            "p_value": None,
            "direction": "insufficient_data",
            "change_per_year": None,
        }

    x = np.array([p[0] for p in valid_pairs], dtype=float)
    y = np.array([p[1] for p in valid_pairs], dtype=float)

    result = stats.linregress(x, y)
    slope = float(result.slope)
    p_value = float(result.pvalue)
    r_squared = float(result.rvalue ** 2)
    change_per_year = round(slope, 4)

    # Classify direction (issue #58: also checks R²)
    min_change = MIN_ANNUAL_CHANGE.get(metric_name, 0.1)
    direction = _classify_trend(slope, p_value, r_squared, metric_name, min_change)

    return {
        "years": years,
        "values": values,
        "slope": round(slope, 6),
        "p_value": round(p_value, 4),
        "r_squared": round(r_squared, 4),
        "direction": direction,
        "change_per_year": change_per_year,
    }


def _classify_trend(
    slope: float,
    p_value: float,
    r_squared: float,
    metric_name: str,
    min_change: float,
) -> str:
    """
    Classify a metric's trend as improving, stable, or declining.

    The meaning of "improving" depends on the metric:
    - Wait time: negative slope = improving (shorter waits)
    - Volume: positive slope = improving (more transplants)
    - Survival: positive slope = improving (better outcomes)
    - Mortality/delisting: negative slope = improving (fewer adverse events)
    """
    # Not significant → stable
    if p_value > P_VALUE_THRESHOLD:
        return "stable"

    # R² too low → statistically significant but practically meaningless (issue #58)
    if r_squared < MIN_R_SQUARED:
        return "stable"

    # Slope too small to be meaningful
    if abs(slope) < min_change:
        return "stable"

    # Determine if the direction is "good" or "bad"
    # For metrics where lower is better (wait time, mortality, delisting)
    lower_is_better = metric_name in ("median_wait_months", "mortality_rate", "delisting_rate")

    if lower_is_better:
        return "improving" if slope < 0 else "declining"
    else:
        return "improving" if slope > 0 else "declining"


def _overall_direction(trends: dict[str, dict]) -> str:
    """
    Compute overall trend from individual metric trends.

    Uses a simple voting system weighted by importance:
    - wait_time_trend: weight 3 (most important for patients)
    - volume_trend: weight 2
    - graft_survival_trend: weight 2
    - mortality_rate_trend: weight 1
    """
    weights = {
        "wait_time": 3,
        "volume": 2,
        "graft_survival": 2,
        "mortality_rate": 1,
    }

    score = 0
    total_weight = 0

    for key, weight in weights.items():
        trend = trends.get(key + "_trend")
        if not trend or trend.get("direction") == "insufficient_data":
            continue
        total_weight += weight
        if trend["direction"] == "improving":
            score += weight
        elif trend["direction"] == "declining":
            score -= weight

    if total_weight == 0:
        return "insufficient_data"

    ratio = score / total_weight
    if ratio > 0.2:
        return "improving"
    elif ratio < -0.2:
        return "declining"
    return "stable"


def get_city_trends(organ: str, city: str) -> dict | None:
    """
    Get trend analysis for a specific city and organ.

    Returns dict with trend data for each metric, sparkline data,
    and overall direction. Returns None if no historical data available.
    """
    if organ not in VALID_ORGANS:
        return None

    data = _get_historical_data()
    if not data:
        return None

    city_data = data.get("cities", {}).get(city, {}).get(organ)
    if not city_data:
        return None

    years = city_data.get("years", [])
    if not years:
        return None

    # Compute trends for each metric
    trends = {}

    # Wait time trend
    trends["wait_time_trend"] = _compute_metric_trend(
        years, city_data.get("median_wait_months", []), "median_wait_months"
    )

    # Volume trend
    trends["volume_trend"] = _compute_metric_trend(
        years, city_data.get("volume", []), "volume"
    )

    # Graft survival trend
    trends["graft_survival_trend"] = _compute_metric_trend(
        years, city_data.get("graft_survival_1yr", []), "graft_survival_1yr"
    )

    # Mortality rate trend
    trends["mortality_rate_trend"] = _compute_metric_trend(
        years, city_data.get("mortality_rate", []), "mortality_rate"
    )

    # Overall direction
    trends["overall_direction"] = _overall_direction(trends)

    # Sparkline data (compact format for frontend charting)
    trends["sparklines"] = {
        "years": years,
        "wait_time": city_data.get("median_wait_months", []),
        "volume": city_data.get("volume", []),
        "graft_survival": city_data.get("graft_survival_1yr", []),
    }

    # National comparison data
    national = data.get("national", {}).get(organ)
    if national:
        trends["national"] = {
            "years": national.get("years", []),
            "wait_time": national.get("median_wait_months", []),
            "graft_survival": national.get("graft_survival_1yr", []),
        }

    trends["city"] = city
    trends["organ"] = organ

    return trends


def get_all_trends(organ: str) -> dict[str, dict]:
    """
    Get trend analysis for all cities for a given organ.

    Returns dict of city_name → trend_data.
    """
    if organ not in VALID_ORGANS:
        return {}

    data = _get_historical_data()
    if not data:
        return {}

    result = {}
    for city in data.get("cities", {}):
        trend = get_city_trends(organ, city)
        if trend:
            result[city] = trend

    return result
