#!/usr/bin/env python3
"""Forecast-quality gate (#308).

Reads docs-site/static/data/temporal-forecast.json (regenerated by
scripts/run-temporal-forecast.py) and fails if the 12-month out-of-sample
rank concordance for any gated organ drops below its floor.

Floors sit ~0.08-0.10 below the 2026-08-25 medians (kidney 0.846,
liver 0.794, pancreas 0.812, heart 0.704, lung 0.638) so routine data
refreshes pass, while a pipeline regression — a parser change corrupting
factors, an archive release parsed wrong, a model change that destroys
predictive ordering — fails loudly.

Usage:
    python scripts/check-forecast-gate.py            # gate on the JSON
Exit code 0 = pass, 1 = a floor was breached or the report is malformed.
"""
import json
import sys
from pathlib import Path

REPORT = Path(__file__).parent.parent / "docs-site" / "static" / "data" / "temporal-forecast.json"

# organ -> (floor for median_rho_forecast at 12mo, minimum n_pairs)
FLOORS = {
    "kidney": (0.75, 8),
    "liver": (0.70, 8),
    "pancreas": (0.70, 4),
    "heart": (0.60, 8),
    "lung": (0.52, 8),
    # intestine: too few centers for a stable rho — reported, not gated
}


def main() -> int:
    if not REPORT.exists():
        print(f"GATE FAIL: {REPORT} missing — run scripts/run-temporal-forecast.py first")
        return 1
    summary = json.loads(REPORT.read_text()).get("summary", {})
    failures = []
    for organ, (floor, min_pairs) in FLOORS.items():
        h = summary.get(organ, {}).get("12mo", {})
        rho = h.get("median_rho_forecast")
        n_pairs = h.get("n_pairs")
        if rho is None or n_pairs is None:
            failures.append(f"{organ}: 12mo forecast summary missing from report")
            continue
        status = "OK " if (rho >= floor and n_pairs >= min_pairs) else "FAIL"
        print(f"[{status}] {organ:9s} 12mo rho={rho:.3f} (floor {floor}) "
              f"pairs={n_pairs} (min {min_pairs})")
        if rho < floor:
            failures.append(f"{organ}: rho {rho:.3f} < floor {floor}")
        if n_pairs < min_pairs:
            failures.append(f"{organ}: only {n_pairs} train/test pairs (< {min_pairs})")
    if failures:
        print("\nGATE FAIL:")
        for f in failures:
            print(f"  - {f}")
        return 1
    print("\nForecast gate passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
