#!/usr/bin/env python3
"""Recompute the clinical-assumptions-register summary counts (#335).

The register's header line states how many assumptions are tracked, how many
are unjustified, and how many are high-risk. Nothing recomputed those numbers,
so they drifted: the header claimed 129 tracked while the file held 249 IDs.

Two wrinkles this handles that a naive parse gets wrong:
  * Sections 1-7 are 7-column tables; section 8 ("cross-cutting validation
    evidence") is 6-column, so Status/Risk live at different indices.
  * Section 8 rows are recorded EVIDENCE, not open assumptions, so they are
    counted separately and excluded from the assumption totals.

Run with --check (CI / pytest) to verify without writing.
"""
import argparse
import re
import sys
from pathlib import Path

REGISTER = Path(__file__).parent.parent / "docs" / "clinical-assumptions-register.md"
UNJUSTIFIED = {"uncited", "assumed", "heuristic_clamp"}
# Rows marked resolved describe a defect that has been FIXED. They stay in
# the register for the audit trail but must not inflate the outstanding
# counts, or the header overstates how much work is left.
RESOLVED = "resolved"
EVIDENCE_SECTION = "## 8."


def parse(text: str) -> tuple[dict, dict]:
    """(assumptions, evidence) as {id: {"status", "risk"}}."""
    assumptions: dict[str, dict] = {}
    evidence: dict[str, dict] = {}
    in_evidence = False
    for line in text.splitlines():
        if line.startswith("## "):
            in_evidence = line.startswith(EVIDENCE_SECTION)
            continue
        m = re.match(r"^\|\s*([A-Z]+-\d+)\s*\|(.*)$", line)
        if not m:
            continue
        rid, rest = m.group(1), m.group(2)
        # Split on UNESCAPED pipes only: several rows legitimately contain a
        # pipe in prose (conditional-probability notation, |learned_corr|),
        # written as \| per Markdown. Splitting naively shifted every cell
        # after it and silently mis-read those rows' Status.
        cells = [c.strip() for c in re.split(r"(?<!\\)\|", rest)]
        # 7-col: Location, Assumption, Basis, Status, Risk, Notes -> 3, 4
        # 6-col: Location, Assumption/Result, Status, Risk, Notes  -> 2, 3
        si, ri = (2, 3) if in_evidence else (3, 4)
        if len(cells) <= ri:
            continue
        rec = {"status": cells[si], "risk": cells[ri]}
        target = evidence if in_evidence else assumptions
        target.setdefault(rid, rec)
    return assumptions, evidence


def summarize(assumptions: dict) -> tuple[int, int, int, int]:
    open_rows = [r for r in assumptions.values() if r["status"] != RESOLVED]
    total = len(assumptions)
    resolved = total - len(open_rows)
    unjust = sum(1 for r in open_rows if r["status"] in UNJUSTIFIED)
    high = sum(1 for r in open_rows if r["risk"] == "high")
    return total, unjust, high, resolved


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the header matches without rewriting it")
    args = ap.parse_args()

    text = REGISTER.read_text()
    assumptions, evidence = parse(text)
    total, unjust, high, resolved = summarize(assumptions)

    line = (f"**Summary:** **{total}** assumptions tracked "
            f"(plus {len(evidence)} recorded validation-evidence entries in "
            f"section 8). **{unjust}** still need justification "
            f"(`uncited` + `assumed` + `heuristic_clamp`). **{high}** are "
            f"flagged **high-risk** (`risk_if_wrong = high`), excluding "
            f"{resolved} rows marked `resolved`; the high-risk "
            f"entries that are also unjustified form the priority shortlist at "
            f"the end. Counts are regenerated by "
            f"`scripts/check-register.py` — do not hand-edit them.")

    current = next((ln for ln in text.splitlines()
                    if ln.startswith("**Summary:**")), None)
    if current is None:
        print("ERROR: no '**Summary:**' line in the register", file=sys.stderr)
        return 1

    if current == line:
        print(f"register summary current: {total} assumptions, "
              f"{unjust} unjustified, {high} high-risk")
        return 0
    if args.check:
        print("ERROR: register summary is stale.\n"
              f"  have: {current}\n  want: {line}\n"
              "Run: python scripts/check-register.py", file=sys.stderr)
        return 1

    REGISTER.write_text(text.replace(current, line))
    print(f"register summary updated: {total} assumptions, "
          f"{unjust} unjustified, {high} high-risk "
          f"({len(evidence)} evidence entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
